### PR TITLE
Close #18 : Export csv

### LINKED ISSUE #18: Add export data feature
Pls add a possibility to export the data collected by the app.

### PR DESCRIPTION
**Pull request by JonathanMM**
Add the possibility to export step count in a csv file

### CODE REVIEW

**Comment by Yonjuni** [comment]
Thanks for this PR. We are currently working on a bigger update, which also includes changes in the DB. Therefore, I'd like to hold this PR until the update is done. I'll notify you then, okay?

**Comment by JonathanMM** [comment]
Yeah, sure, no problem ;)

**Comment by matthiasbeyer** [comment]
Awesome. Hopefully this lands soonish! Thanks for implementing this!

**Comment by vanyasem** [comment]
are you still working on your "bigger update"? I can help you to resolve the merge conflict, as I have an urge to backup my data from the F-Droid version of Pedometer

**Comment by pyramid3d** [comment]
Is this project still active?
If not, can the ownerallow other maintainers or transfer the project?
Thanks

**Comment by kolaente** [comment]
Any updates on this?

**Comment by petermayer** [comment]
Hi everyone! Yes, we are still working on the update and we are aware that it has been a long time! We are currently working on a harmonised way to backup and sync the information in multiple apps.

**Comment by skysphr** [comment]
Is this update still on the roadmap?

**Comment by petermayer** [comment]
Hey, we are currently in the process to roll out the exporting and backup features into all PFAs (see [here](https://github.com/SecUSo/privacy-friendly-backup) for the basic infrastructure behind this rollout). So yes, this is still on the roadmap and will in the not too distant future make its way in the pedometer app 👍

**Pull request merged**
