### PR TITLE
Added Spanish translation and fixed small mistake on English

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Also note that (this affects any language) the " (active)" string is trimmed, and so it appears next to the currently selected walking mode (i.e. "Walking(active)" rather than "Walking (active)").

**Comment by XyLoNaMiyX** [comment]
Might I ask why it wasn't merged @Yonjuni? I'd like to hear, thanks anyway.

**Comment by Yonjuni** [comment]
@XyLoNaMiyX Sure ;) We have someone who checks that there is no problem with the translation of the disclaimer. The person with knowledge for Spanish is very busy right now. The Japanese translations can be checked quicker because I can speak Japanese. 
I guess it will be merged after Christmas before next year. 
We overall don't think that there will be some problems resulting with the translations, but have to be sure regarding the about page.

**Comment by Yonjuni** [comment]
Ah I see, the issue has been closed automatically, because we have rearranged our branch structure.

**Comment by XyLoNaMiyX** [comment]
Awesome! I thought I had done something wrong :P

**Comment by licaon-kter** [comment]
@Yonjuni So you have someone for every language? :)

**Comment by Yonjuni** [comment]
So far, yes.

**Pull request merged**
