### PR TITLE
Made widgets vertically resizeable

### PR DESCRIPTION
**Pull request by leo030303**
#121 Make widget vertically resizeable
First time contributing to an open source project, I read the contribution guidelines and hope I'm doing it right, thanks for a great app!

### CODE REVIEW

**Review by morckx — COMMENTED** [review]
For me (Android 13 / LineageOS 20) also minHeight or maybe just minResizeHeight has to be reduced to make the widget less tall. 

Can you test this on emulators?

**Comment by leo030303** [comment]
Tested it on an emulated pixel 6a with android 13 and I had no issue to resizing to 1 row high with the max 5 rows. I also tested it on my device with android 13 and neo launcher and set the number of rows to 16 and it still stayed one row high (ignore the appearance of the widget itself, I edited the font size and background colour but I didn't change the minHeight or minResizeHeight values)

neo_launcher
screen_bigger_grid

**Comment by morckx** [comment]
> Tested it on an emulated pixel 6a with android 13 and I had no issue to resizing to 1 row high with the max 5 rows. I also tested it on my device with android 13 and neo launcher and set the number of rows to 16 and it still stayed one row high (ignore the appearance of the widget itself, I edited the font size and background colour but I didn't change the minHeight or minResizeHeight values)
> 

Thanks for testing! Is there a special reason why you want to make the widget higher than 1 row? The content is only one row high, anyway, isn't it?

For me your addition helps when I add `android:minResizeHeight="20dp"`, but that's just because of an apparent bug in the LineageOS default launcher Trebuchet which otherwise makes the widget 1 columns x 5 rows, i.e. too tall to be usable.

**Comment by leo030303** [comment]
I don't actually need to make it higher than 1 row this was just a workaround as it defaulted to 2 high, if the default was 1 high that would work fine too, I guess the utility of keeping it resizeable vertically would be for if there was a bug with some launcher that messed up the default, like you said with trebuchet, it let's you fix it easily enough

**Comment by morckx** [comment]
> I don't actually need to make it higher than 1 row this was just a workaround as it defaulted to 2 high, if the default was 1 high that would work fine too, I guess the utility of keeping it resizeable vertically would be for if there was a bug with some launcher that messed up the default, like you said with trebuchet, it let's you fix it easily enough

OK, sorry, you wrote this in your initial issue. I was confused because that the widget cell height is wrong in some launchers is now, that we know it, a slightly different issue for which we can also provide a better fix (more later...).

**Pull request closed without merging**
